### ISSUE TITLE
Settlers and Elves spawns in deep water.

### ISSUE THREAD

**Issue by AngelQC** [RustyMods/VikingNPC#7]
I keep seeing and getting greeted or attacked (seldom) by swimming vikings all over the place, As far as I can think, they even spawn in Ocean, but I will have another look to make sure.

Raiders and Raider ships are deactivated, if it may help, Settlers and Elves are enabled.

**Comment by AngelQC** [comment]
I just noticed, while reading another issue, that the Elves were set to spawn in Ocean, so are Raiders.
I un-checked from both, I'll see what happens.
Could be default settings messed up (I did not set that)

**Comment by AngelQC** [comment]
Well, it seems to have resolved the issue.  I suggest to leave it open and maybe test the default configuration.  Could be the first launch behavior or the use of the "Configuration Manager" misinterpreting the file ?
The map was created while the mod was active, if this can be of any help.

**Comment by AngelQC** [comment]
As I keep seeing Vikings in water, but in other biomes, I modifier the minimum altitude from -1000 to -100, to see what the change will be.
What is the meaning of this number?  -1000 meters, which would indeed be under the water line ?

**Comment by RustyMods** [comment]
-1000 to 1000 are default numbers.

you should be able to config elf spawns to not spawn in ocean which should resolve this.

**Comment by AngelQC** [comment]
Hello @RustyMods,
The -## altitude makes it that vikings do spawn in water still, but closer to shore in other biomes, like Forest for example.  
I have just set "Minimal altitude" to "1" for everything, but for ships, this should makes sure Viking never spawn in any kind of water.

**Comment by RustyMods** [comment]
yes, sounds good. also, just for information sake - ships will snap to water level when spawning

**Comment by AngelQC** [comment]
I'm still seeing vikings in water, but much less so.  Maybe they spawn is very small islands and go swimming ?  Speaking of which, I have never seen one standing alone in a small island, unlike vanilla spawns (Troll, deer, ...) for example.  That's good :)
